[build]
builder = "nixpacks"

[build.nixpacks]
installCmd = "npm install"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/health"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
